[package]
name = "pokerlogic"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.10"

[dependencies.bevy]
version = "0.19"
default-features = false
features = [
    "bevy_asset",
    "bevy_core_pipeline",
    "bevy_log",
    "bevy_picking",
    "bevy_post_process",  # needed because MSAA makes the camera layers work for some reason
    "bevy_render",
    "bevy_ui",
    "bevy_ui_render",
    "bevy_winit",
    "std",
    "ui_picking",
    "webgl2",
]

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.4", default-features = false, features = [
    "wasm_js",
] }
wasm-bindgen = { version = "0.2" }
web-sys = { version = "0.3", features = ["Window"] }

[dev-dependencies]
allocation-counter = { version = "0" }
